# MVC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///myvote
    username: root
    password: 123456

  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  thymeleaf:
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  type-aliases-package: com.springboot.pojo
  configuration:
    auto-mapping-behavior: FULL
    use-generated-keys: true

